### ISSUE TITLE
Tarea 

### ISSUE THREAD

**Issue by yaritzaov123** [SistemasTecTlaxiaco/infografia-yaritzaov123#2]
[infografia de sistemas numericos.docx](https://github.com/SistemasTecTlaxiaco/infografia-yaritzaov123/files/7198265/infografia.de.sistemas.numericos.docx)

**Comment by yanet02** [comment]
20%
Tu trabajo esta bien hecha! Contiene datos muy buenos!!

**Comment by josealfredo79** [comment]
No se puede visualizar la tarea...favor de subir....nuevamente...

**Comment by yaritzaov123** [comment]
[infografia de sistemas numericos.docx](https://github.com/SistemasTecTlaxiaco/infografia-yaritzaov123/files/7198269/infografia.de.sistemas.numericos.docx)

**Comment by yaritzaov123** [comment]
[infografia de sistemas numericos.docx](https://github.com/SistemasTecTlaxiaco/infografia-yaritzaov123/files/7207235/infografia.de.sistemas.numericos.docx)
